### ISSUE TITLE
Dead Reckoning Algorithm Table

### ISSUE THREAD

**Issue by bleckers** [open-dis/DISTutorial#18]
The table in the [Dead Reckoning wiki page](https://github.com/open-dis/DISTutorial/wiki/Dead-Reckoning) should read:

Value | Description
-- | --
0 | Other
1 | Static (Entity does not move.)
2 | DRM(F, P, W)
3 | DRM(R, P, W)
4 | DRM(R, V, W)
5 | DRM(F, V, W)
6 | DRM(F, P, B)
7 | DRM(R, P, B)
8 | DRM(R, V, B)
9 | DRM(F, V, B)

It looks like 3 and 4 have been duplicated (remove the dup) and the additional "DRM(F, P, W)" in 1 should be shifted down.

**Comment by leif81** [comment]
Thank-you @bleckers It's been fixed in the wiki now.

Diff here: https://github.com/open-dis/dis-tutorial/wiki/Dead-Reckoning/_compare/8b5269208965f17db4ec733409a135aa38ac5aa4
